language: julia

os:
  - linux

julia:
  - 0.4
  - nightly

env:
  - MPI=mpich2
  - MPI=openmpi

notifications:
  email: false

before_install:
  - sudo add-apt-repository -y ppa:staticfloat/julia-deps
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq -y
  - curl http://cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
  - sudo apt-get install -qq -y gfortran mpich2 libmpich2-3 libmpich2-dev gcc-4.9 g++-4.9 gfortran-4.9 libstdc++-4.9-dev
  - export CC=gcc-4.9
  - export CXX=g++-4.9
  - export CPU_CORES=2

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("MPI"); Pkg.build("MPI")'
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Elemental"); dlopen("/home/travis/.julia/v0.4/Elemental/deps/usr/lib/libEl.so"); Pkg.test("Elemental")'
